#ifndef VGA_H
#define VGA_H

#define PALETTE_INDEX       0x03c8
#define PALETTE_DATA        0x03c9

#define VGA_MEMORY_BASE   0x000A0000
#define VGA_MEMORY_LENGTH 0x00010000

#define VGA_COLOR_BLACK     0x00
#define VGA_COLOR_BLUE      0x01
#define VGA_COLOR_GREEN     0x02
#define VGA_COLOR_CYAN      0x03
#define VGA_COLOR_RED       0x04
#define VGA_COLOR_MAGENTA   0x05
#define VGA_COLOR_BROWN     0x06
#define VGA_COLOR_LIGHTGRAY 0x07
#define VGA_COLOR_DARKGRAY  0x08
#define VGA_COLOR_LIGHTBLUE 0x09
#define VGA_COLOR_LIGHTGREEN 0x0a
#define VGA_COLOR_LIGHTCYAN 0x0b
#define VGA_COLOR_LIGHTMAGENTA 0x0d
#define VGA_COLOR_YELLOW    0x0e
#define VGA_COLOR_WHITE     0x0f
#define VGA_COLOR_GRAY0     0x10
#define VGA_COLOR_GRAY1     0x11
#define VGA_COLOR_GRAY2     0x12
#define VGA_COLOR_GRAY3     0x13
#define VGA_COLOR_GRAY4     0x14
#define VGA_COLOR_GRAY5     0x15
#define VGA_COLOR_GRAY6     0x16
#define VGA_COLOR_GRAY7     0x17
#define VGA_COLOR_GRAY8     0x18
#define VGA_COLOR_GRAY9     0x19
#define VGA_COLOR_GRAY10    0x1a
#define VGA_COLOR_GRAY11    0x1b
#define VGA_COLOR_GRAY12    0x1c
#define VGA_COLOR_GRAY13    0x1d
#define VGA_COLOR_GRAY14    0x1e
#define VGA_COLOR_GRAY15    0x1f
#define VGA_COLOR_BLUE2     0x20
#define VGA_COLOR_BLUE3     0x21
#define VGA_COLOR_PURPLE    0x22
#define VGA_COLOR_PURPLEPINK 0x23
#define VGA_COLOR_PINK      0x24
#define VGA_COLOR_PINK2     0x25
#define VGA_COLOR_PINK3     0x26
#define VGA_COLOR_LIGHTRED  0x27
#define VGA_COLOR_LIGHTRED2 0x28
#define VGA_COLOR_REDBROWN  0x29
#define VGA_COLOR_LIGHTBROWN 0x2a
#define VGA_COLOR_LIGHTBROWN2 0x2b
#define VGA_COLOR_YELLOW2     0x2c
#define VGA_COLOR_YELLOWGREEN 0x2d
#define VGA_COLOR_LIGHTGREEN0 0x2e
#define VGA_COLOR_LIGHTGREEN1 0x2f
#define VGA_COLOR_LIGHTGREEN2 0x30
#define VGA_COLOR_LIGHTGREEN3 0x31
#define VGA_COLOR_BLUEGREEN   0x32
#define VGA_COLOR_LIGHTBLUE0  0x33
#define VGA_COLOR_LIGHTBLUE1  0x34
#define VGA_COLOR_LIGHTBLUE2  0x35
#define VGA_COLOR_LIGHTBLUE3  0x36
#define VGA_COLOR_LIGHTBLUE4  0x37
#define VGA_COLOR_PINKBLUE0   0x38
#define VGA_COLOR_PINKBLUE1   0x39
#define VGA_COLOR_PINKBLUE2   0x3a
#define VGA_COLOR_PINKBLUE3   0x3b
#define VGA_COLOR_LIGHTPINK0  0x3c
#define VGA_COLOR_LIGHTPINK1  0x3d
#define VGA_COLOR_LIGHTPINK2  0x3e
#define VGA_COLOR_LIGHTPINK3  0x3f
#define VGA_COLOR_PINKBROWN0  0x40
#define VGA_COLOR_PINKBROWN1  0x41
#define VGA_COLOR_PINKBROWN2  0x42
#define VGA_COLOR_PINKBROWN3  0x43
#define VGA_COLOR_LIGHTYELLOW3 0x44
#define VGA_COLOR_YELLOWGREEN0 0x45
#define VGA_COLOR_YELLOWGREEN1 0x46
#define VGA_COLOR_YELLOWGREEN2 0x47
#define VGA_COLOR_YELLOWGREEN3 0x48
#define VGA_COLOR_GREENYAN0 0x49
#define VGA_COLOR_GREENYAN1 0x4a
#define VGA_COLOR_GREENYAN2 0x4b
#define VGA_COLOR_LIGHTCYAN0 0x4c
#define VGA_COLOR_LIGHTCYAN1 0x4d
#define VGA_COLOR_LIGHTPURPLE0 0x4e
#define VGA_COLOR_LIGHTPURPLE1 0x4f
#define VGA_COLOR_BRIGHTPURPLE0 0x50
#define VGA_COLOR_BRIGHTPURPLE1 0x51
#define VGA_COLOR_BRIGHTPURPLERED0 0x52
#define VGA_COLOR_BRIGHTPURPLERED1 0x53
#define VGA_COLOR_BRIGHTPINK0 0x54
#define VGA_COLOR_BRIGHTPINK1 0x55
#define VGA_COLOR_BRIGHTPINK2 0x56
#define VGA_COLOR_BRIGHTPINK3 0x57
#define VGA_COLOR_BRIGHTPINK4 0x58
#define VGA_COLOR_BRIGHTPINK5 0x59
#define VGA_COLOR_BRIGHTPINKYELLOW 0x5a
#define VGA_COLOR_BRIGHTYELLOW0 0x5b
#define VGA_COLOR_BRIGHTYELLOW1 0x5c
#define VGA_COLOR_BRIGHTYELLOWGREEN0 0x5d
#define VGA_COLOR_BRIGHTYELLOWGREEN1 0x5e
#define VGA_COLOR_BRIGHTYELLOWGREEN2 0x5f
#define VGA_COLOR_BRIGHTCYAN0 0x60
#define VGA_COLOR_BRIGHTCYAN1 0x61
#define VGA_COLOR_BRIGHTCYAN2 0x62
#define VGA_COLOR_BRIGHTCYAN3 0x63
#define VGA_COLOR_BRIGHTCYAN4 0x64
#define VGA_COLOR_BRIGHTCYAN5 0x65
#define VGA_COLOR_BRIGHTCYAN6 0x66
#define VGA_COLOR_BRIGHTCYAN7 0x67

#define VGA_WIDTH_MAX 320
#define VGA_HEIGHT_MAX 200

typedef struct tagBITMAPFILEHEADER { // bmfh  
	UINT16    bfType; 
	UINT32   bfSize; 
	UINT16    bfReserved1; 
	UINT16    bfReserved2; 
	UINT32   bfOffBits; 
} BITMAPFILEHEADER; 

typedef struct tagBITMAPINFOHEADER{ // bmih  
   INT32  biSize; 
   INT32   biWidth; 
   INT32   biHeight; 
   INT16   biPlanes; 
   INT16   biBitCount;
   INT32  biCompression; 
   INT32  biSizeImage; 
   INT32   biXPelsPerMeter; 
   INT32   biYPelsPerMeter; 
   UINT32  biClrUsed; 
   UINT32  biClrImportant; 
} BITMAPINFOHEADER; 

typedef struct tagRGBQUAD { // rgbq  
    UINT8    rgbBlue; 
    UINT8    rgbGreen; 
    UINT8    rgbRed; 
    UINT8    rgbReserved; 
} RGBQUAD; 

#define RGB(r,g,b) ((((UINT32)r)<<0) | (((UINT32)g)<<8) | (((UINT32)b)<<16))
#define PIX_OFFSET 0X436
#define Width_OFFSET 0X12
#define Height_OFFSET 0X16
#define Size_OFFSET 0X22
#define STRING_SIZE 12

typedef struct{
   EFI_GRAPHICS_OUTPUT_PROTOCOL *EFI_GOP;
   UINT8 *pVideoMemory;
   EFI_GRAPHICS_OUTPUT_BLT_PIXEL *pPixMemory;
   UINT8 BitsPerPixel;
   GRAPHIC_AREA Area;
}VGA_CONTROL;

//extern VGA_CONTROL VgaCtrl;
extern VGA_CONTROL *pOsDriverVga;
VOID VgaInit(VOID);
EFI_GRAPHICS_OUTPUT_BLT_PIXEL Bmp2Rgb(UINT8 bmp);
VOID BmpDraw(UINT8* bmp, UINT32 size, UINT16 Start_x, UINT16 Start_y, BOOLEAN DrawOsd);
VOID BoxDraw(UINT8 color, UINT32 Width, UINT32 Height, UINT16 x, UINT16 y);
VOID PixelBmpArraySet(EFI_GRAPHICS_OUTPUT_BLT_PIXEL* pixArr, UINT8* bmp);
VOID PixelArrayDraw(EFI_GRAPHICS_OUTPUT_BLT_PIXEL* pixArr, UINT16 Start_x, UINT16 Start_y, UINT32 width, UINT32 height);
VOID PixelArrayCopy(EFI_GRAPHICS_OUTPUT_BLT_PIXEL* source, EFI_GRAPHICS_OUTPUT_BLT_PIXEL* dest, UINT32 len);
VOID PixelArraySet(EFI_GRAPHICS_OUTPUT_BLT_PIXEL* source, EFI_GRAPHICS_OUTPUT_BLT_PIXEL color, UINT32 len);
VOID PixelArray256Set(EFI_GRAPHICS_OUTPUT_BLT_PIXEL* source, UINT8 color, UINT32 len);
VOID VgaTextBufferClear(VOID);
VOID F_VgaTextBufferSet(UINT8 Value);
VOID F_VgaTextReset(VOID);
VOID F_VgaTextDirtySet(VOID);
VOID F_VgaTextReadySet(VOID);
VOID F_VgaTextScrollDown(VOID);

#endif