#ifndef  GFX_CLUT_H
#define  GFX_CLUT_H

#define GFX_COLOR_MAX 85

#define PALETTE_WHITE        0xff
#define PALETTE_CYAN         0xfe
#define PALETTE_PINK         0xfd
#define PALETTE_BLUE         0xfc
#define PALETTE_YELLOW       0xfb
#define PALETTE_GREEN        0xfa
#define PALETTE_RED          0xf9
#define PALETTE_DEEPGRAY     0xf8
#define PALETTE_GRAY         0xf7
#define PALETTE_DRAKGRAY     0x52
#define PALETTE_WHITE2       0xf6
#define PALETTE_CYAN5        0xf5
#define PALETTE_CYAN4        0xf4
#define PALETTE_CYAN3        0xf3
#define PALETTE_CYAN2        0xf2
#define PALETTE_CYAN1        0xf1
#define PALETTE_CYAN0        0xf0
#define PALETTE_YELLOW0      0x37
#define PALETTE_YELLOW1      0x3f
#define PALETTE_YELLOW2      0x47
#define PALETTE_YELLOW3      0x4f
#define PALETTE_YELLOW4      0x77 
#define PALETTE_RED0         0x16
#define PALETTE_RED1         0x17
#define PALETTE_RED2         0x1e
#define PALETTE_RED3         0x1f
#define PALETTE_RED4         0x26
#define PALETTE_RED5         0x27
#define PALETTE_RED6         0x2e
#define PALETTE_RED7         0x2f
#define PALETTE_PINK0        0x86
#define PALETTE_PINK1        0x87
#define PALETTE_PINK2        0x8e
#define PALETTE_PINK3        0x8f
#define PALETTE_PINK4        0x96
#define PALETTE_PINK5        0x97
#define PALETTE_PINK6        0x9e
#define PALETTE_PINK7        0x9f
#define PALETTE_DEEPGREEN0   0x10 
#define PALETTE_DEEPGREEN1   0x11
#define PALETTE_DEEPGREEN2   0x18
#define PALETTE_DEEPGREEN3   0x19
#define PALETTE_GREEN0       0x20
#define PALETTE_GREEN1       0x21
#define PALETTE_GREEN3       0x28
#define PALETTE_GREEN4       0x29
#define PALETTE_LIGHTGREEN0  0x30
#define PALETTE_LIGHTGREEN1  0x31
#define PALETTE_LIGHTGREEN2  0x38
#define PALETTE_LIGHTGREEN3  0x39
#define PALETTE_YELLOWGREEN0 0x35
#define PALETTE_YELLOWGREEN1 0x36
#define PALETTE_YELLOWGREEN2 0x3d
#define PALETTE_YELLOWGREEN3 0x3e
#define PALETTE_YELLOWGREEN4 0x45
#define PALETTE_YELLOWGREEN5 0x46
#define PALETTE_YELLOWGREEN6 0x4d
#define PALETTE_YELLOWGREEN7 0x4e
#define PALETTE_DARKBLUE0    0x40
#define PALETTE_DARKBLUE1    0x41
#define PALETTE_DARKBLUE2    0x48
#define PALETTE_DARKBLUE3    0x49
#define PALETTE_BLUE0        0xc0
#define PALETTE_BLUE1        0xc1
#define PALETTE_BLUE2        0xc8
#define PALETTE_BLUE3        0xc9 
#define PALETTE_LIGHTBLUE0   0xe2
#define PALETTE_LIGHTBLUE1   0xe3
#define PALETTE_LIGHTBLUE2   0xe9
#define PALETTE_LIGHTBLUE3   0xea
#define PALETTE_LIGHTBLUE4   0xeb
#define PALETTE_BROWN5       0x0f
#define PALETTE_BROWN4       0x0e
#define PALETTE_BROWN3       0x0d
#define PALETTE_BROWN2       0x0c
#define PALETTE_BROWN1       0x0b
#define PALETTE_BROWN0       0x0a
#define PALETTE_LIGHTBLUE    0x09
#define PALETTE_LIGHTCYAN    0x08
#define PALETTE_LIGHTPURPLE  0x07
#define PALETTE_DEEPCYAN     0x06
#define PALETTE_DEEPPURPLE   0x05
#define PALETTE_DEEPBLUE     0x04
#define PALETTE_DEEPOLIVE    0x03
#define PALETTE_DEEPGREEN    0x02 
#define PALETTE_BROWN        0x01
#define PALETTE_BLACK        0x00

typedef enum{
GFX_COLOR_WHITE=0,      //0xff
GFX_COLOR_CYAN,         //0xfe
GFX_COLOR_PINK,         //0xfd
GFX_COLOR_BLUE,         //0xfc
GFX_COLOR_YELLOW,       //0xfb
GFX_COLOR_GREEN,        //0xfa
GFX_COLOR_RED,          //0xf9
GFX_COLOR_DEEPGRAY,     //0xf8
GFX_COLOR_GRAY,         //0xf7
GFX_COLOR_WHITE2,       //0xf6
GFX_COLOR_CYAN5,        //0xf5
GFX_COLOR_CYAN4,        //0xf4
GFX_COLOR_CYAN3,        //0xf3
GFX_COLOR_CYAN2,        //0xf2
GFX_COLOR_CYAN1,        //0xf1
GFX_COLOR_CYAN0,        //0xf0
GFX_COLOR_YELLOW0,      //0x37
GFX_COLOR_YELLOW1,      //0x3f
GFX_COLOR_YELLOW2,      //0x47
GFX_COLOR_YELLOW3,      //0x4f
GFX_COLOR_RED0,         //0x16
GFX_COLOR_RED1,         //0x17
GFX_COLOR_RED2,         //0x1e
GFX_COLOR_RED3,         //0x1f
GFX_COLOR_RED4,         //0x26
GFX_COLOR_RED5,         //0x27
GFX_COLOR_RED6,         //0x2e
GFX_COLOR_RED7,         //0x2f
GFX_COLOR_PINK0,        //0x86
GFX_COLOR_PINK1,        //0x87
GFX_COLOR_PINK2,        //0x8e
GFX_COLOR_PINK3,        //0x8f
GFX_COLOR_PINK4,        //0x96
GFX_COLOR_PINK5,        //0x97
GFX_COLOR_PINK6,        //0x9e
GFX_COLOR_PINK7,        //0x9f
GFX_COLOR_DEEPGREEN0,   //0x10 
GFX_COLOR_DEEPGREEN1,   //0x11
GFX_COLOR_DEEPGREEN2,   //0x18
GFX_COLOR_DEEPGREEN3,   //0x19
GFX_COLOR_GREEN0,       //0x20
GFX_COLOR_GREEN1,       //0x21
GFX_COLOR_GREEN3,       //0x28
GFX_COLOR_GREEN4,       //0x29
GFX_COLOR_LIGHTGREEN0,  //0x30
GFX_COLOR_LIGHTGREEN1,  //0x31
GFX_COLOR_LIGHTGREEN2,  //0x38
GFX_COLOR_LIGHTGREEN3,  //0x39
GFX_COLOR_YELLOWGREEN0, //0x35
GFX_COLOR_YELLOWGREEN1, //0x36
GFX_COLOR_YELLOWGREEN2, //0x3d
GFX_COLOR_YELLOWGREEN3, //0x3e
GFX_COLOR_YELLOWGREEN4, //0x45
GFX_COLOR_YELLOWGREEN5, //0x46
GFX_COLOR_YELLOWGREEN6, //0x4d
GFX_COLOR_YELLOWGREEN7, //0x4e
GFX_COLOR_DARKBLUE0,    //0x40
GFX_COLOR_DARKBLUE1,    //0x41
GFX_COLOR_DARKBLUE2,    //0x48
GFX_COLOR_DARKBLUE3,    //0x49
GFX_COLOR_BLUE0,        //0xc0
GFX_COLOR_BLUE1,        //0xc1
GFX_COLOR_BLUE2,        //0xc8
GFX_COLOR_BLUE3,        //0xc9 
GFX_COLOR_LIGHTBLUE0,   //0xe2
GFX_COLOR_LIGHTBLUE1,   //0xe3
GFX_COLOR_LIGHTBLUE2,   //0xe9
GFX_COLOR_LIGHTBLUE3,   //0xea
GFX_COLOR_LIGHTBLUE4,   //0xeb
GFX_COLOR_BROWN5,       //0x0f
GFX_COLOR_BROWN4,       //0x0e
GFX_COLOR_BROWN3,       //0x0d
GFX_COLOR_BROWN2,       //0x0c
GFX_COLOR_BROWN1,       //0x0b
GFX_COLOR_BROWN0,       //0x0a
GFX_COLOR_LIGHTBLUE,    //0x09
GFX_COLOR_LIGHTCYAN,    //0x08
GFX_COLOR_LIGHTGRAY,    //0x07
GFX_COLOR_DEEPCYAN,     //0x06
GFX_COLOR_DEEPPURPLE,   //0x05
GFX_COLOR_DEEPBLUE,     //0x04
GFX_COLOR_DEEPOLIVE,    //0x03
GFX_COLOR_DEEPGREEN,    //0x02 
GFX_COLOR_BROWN,        //0x01
GFX_COLOR_BLACK,        //0x00
}GFX_COLOR_ENUM;

extern const UINT8 GfxPaletteClut[GFX_COLOR_MAX];

#endif
