#ifndef BOMB_H
#define BOMB_H

#define BombTaskIdleState 0
#define BombTaskRunState  1
#define BombtaskStopState 2

#define BombIdleState    0
#define BombInitialState 1
#define BombRunState     2
#define BombCloseState   3

#define BOMB_PATTERN_MAX 10

#define BOMB_WDN_BUTTON0     (WINDOW_WDN_USERDEVICE)
#define BOMB_WDN_BUTTON1     (WINDOW_WDN_USERDEVICE+1)
#define BOMB_WDN_BUTTON2     (WINDOW_WDN_USERDEVICE+2)
#define BOMB_WDN_BUTTON3     (WINDOW_WDN_USERDEVICE+3)
#define BOMB_WDN_BUTTON4     (WINDOW_WDN_USERDEVICE+4)
#define BOMB_WDN_BUTTON5     (WINDOW_WDN_USERDEVICE+5)
#define BOMB_WDN_BUTTON6     (WINDOW_WDN_USERDEVICE+6)
#define BOMB_WDN_BUTTON7     (WINDOW_WDN_USERDEVICE+7)
#define BOMB_WDN_BUTTON8     (WINDOW_WDN_USERDEVICE+8)
#define BOMB_WDN_BUTTON9     (WINDOW_WDN_USERDEVICE+9)
#define BOMB_WDN_BUTTON10    (WINDOW_WDN_USERDEVICE+10)
#define BOMB_WDN_BUTTON11    (WINDOW_WDN_USERDEVICE+11)
#define BOMB_WDN_BUTTON12    (WINDOW_WDN_USERDEVICE+12)
#define BOMB_WDN_BUTTON13    (WINDOW_WDN_USERDEVICE+13)
#define BOMB_WDN_BUTTON14    (WINDOW_WDN_USERDEVICE+14)
#define BOMB_WDN_BUTTON15    (WINDOW_WDN_USERDEVICE+15)
#define BOMB_WDN_BUTTON16    (WINDOW_WDN_USERDEVICE+16)
#define BOMB_WDN_BUTTON17    (WINDOW_WDN_USERDEVICE+17)
#define BOMB_WDN_BUTTON18    (WINDOW_WDN_USERDEVICE+18)
#define BOMB_WDN_BUTTON19    (WINDOW_WDN_USERDEVICE+19)
#define BOMB_WDN_BUTTON20    (WINDOW_WDN_USERDEVICE+20)
#define BOMB_WDN_BUTTON21    (WINDOW_WDN_USERDEVICE+21)
#define BOMB_WDN_BUTTON22    (WINDOW_WDN_USERDEVICE+22)
#define BOMB_WDN_BUTTON23    (WINDOW_WDN_USERDEVICE+23)
#define BOMB_WDN_BUTTON24    (WINDOW_WDN_USERDEVICE+24)

#define BOMB_WDN_BUTTON25     (WINDOW_WDN_USERDEVICE+25)
#define BOMB_WDN_BUTTON26     (WINDOW_WDN_USERDEVICE+26)
#define BOMB_WDN_BUTTON27     (WINDOW_WDN_USERDEVICE+27)
#define BOMB_WDN_BUTTON28     (WINDOW_WDN_USERDEVICE+28)
#define BOMB_WDN_BUTTON29     (WINDOW_WDN_USERDEVICE+29)
#define BOMB_WDN_BUTTON30     (WINDOW_WDN_USERDEVICE+30)
#define BOMB_WDN_BUTTON31     (WINDOW_WDN_USERDEVICE+31)
#define BOMB_WDN_BUTTON32     (WINDOW_WDN_USERDEVICE+32)
#define BOMB_WDN_BUTTON33     (WINDOW_WDN_USERDEVICE+33)
#define BOMB_WDN_BUTTON34     (WINDOW_WDN_USERDEVICE+34)
#define BOMB_WDN_BUTTON35     (WINDOW_WDN_USERDEVICE+35)
#define BOMB_WDN_BUTTON36     (WINDOW_WDN_USERDEVICE+36)
#define BOMB_WDN_BUTTON37     (WINDOW_WDN_USERDEVICE+37)
#define BOMB_WDN_BUTTON38     (WINDOW_WDN_USERDEVICE+38)
#define BOMB_WDN_BUTTON39     (WINDOW_WDN_USERDEVICE+39)
#define BOMB_WDN_BUTTON40     (WINDOW_WDN_USERDEVICE+40)
#define BOMB_WDN_BUTTON41     (WINDOW_WDN_USERDEVICE+41)
#define BOMB_WDN_BUTTON42     (WINDOW_WDN_USERDEVICE+42)
#define BOMB_WDN_BUTTON43     (WINDOW_WDN_USERDEVICE+43)
#define BOMB_WDN_BUTTON44     (WINDOW_WDN_USERDEVICE+44)
#define BOMB_WDN_BUTTON45     (WINDOW_WDN_USERDEVICE+45)
#define BOMB_WDN_BUTTON46     (WINDOW_WDN_USERDEVICE+46)
#define BOMB_WDN_BUTTON47     (WINDOW_WDN_USERDEVICE+47)
#define BOMB_WDN_BUTTON48     (WINDOW_WDN_USERDEVICE+48)
#define BOMB_WDN_BUTTON49     (WINDOW_WDN_USERDEVICE+49)

#define BOMB_WDN_RESTARTBUTTON     (WINDOW_WDN_USERDEVICE+50)
#define BOMB_WDN_CLOSEBUTTON     (WINDOW_WDN_USERDEVICE+51)

typedef struct{
    UINT8 TaskState;
    UINT8 State;
    UINT8 CurrentPattern;
    UINT8 PreviousPattern;
    UINT32 WindowEvent;
    WINDOW_BUTTON RestartButton;
    WINDOW_DEVICE WdRestartButton;
    WINDOW_BUTTON CloseButton;
    WINDOW_DEVICE WdCloseButton;
    WINDOW_BUTTON BombButton[25];
    WINDOW_DEVICE WdBombButton[25];
    WINDOW_TABLE UserTable;
    WINDOW Window;
}BOMB_CONTROL;

void BombInit(BOMB_CONTROL *pBombCtrl);
void BombSvc(BOMB_CONTROL *pBombCtrl);
void BombEventHandler(BOMB_CONTROL *pBomb);
void BombRestart(BOMB_CONTROL *pBomb);
UINT8 BombBombCalculate(BOMB_CONTROL *pBomb,UINT8 BombNumber);
void BombBombOpen(BOMB_CONTROL *pBomb,UINT8 BombNumber);
void BombBombHit(BOMB_CONTROL *pBomb,UINT8 BombNumber);
void BombBombMark(BOMB_CONTROL *pBomb,UINT8 BombNumber);

#endif
